Fix task folder naming
microsoft/google-play-vsts-extension pull request #345
Opened 2022-05-31 20:44 UTC by vmapetr

**Task name**: GooglePlayIncreaseRolloutV2, GooglePlayPromoteV3

**Description**: TBD

**Documentation changes required:** Yes

**Added unit tests:** (Y/N) Yes

**Attached related issue:** https://github.com/microsoft/build-task-team/issues/2702

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/google-play-vsts-extension/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected - in progress

2022-07-11 22:47 UTC, max-zaytsev requested changes
Thanks! Please bump task versions

2022-07-12 09:05 UTC, vmapetr commented
> Thanks! Please bump task versions

Versions are updated. Thanks!

2022-07-12 09:14 UTC, AndreyIvanov42 approved these changes

2022-07-12 10:19 UTC, max-zaytsev approved these changes

2022-07-14 08:40 UTC, merged